global_conflicts:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: global-conflicts-500009
      dataset: raw_conflict_data
      threads: 4
      # This is the magic line that points to the temporary 
      # credentials file we created in the GitHub Action!
      keyfile: /Users/mymac/Projects/learning_dbt/global-conflicts-500009-e9d58d2e16ac.json