name: 'global_conflicts'
version: '1.0.0'
config-version: 2

profile: 'jaffle_shop'

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"
  
models:
  global_conflicts:
    +materialized: view