version: 2

models:
  # ---------------------------------------------------------
  # 1. STAGING MODELS
  # ---------------------------------------------------------
  - name: stg_ucdp_conflicts
    description: "Cleaned and standardized base table for UCDP conflict events."
    columns:
      - name: event_id
        description: "The primary key for a specific conflict event."
        tests:
         - unique
         - not_null
      
      - name: country
        description: "The country where the conflict event took place."
        tests:
          - not_null

      - name: estimated_fatalities
        description: "The best estimate of total fatalities for the event."

  # ---------------------------------------------------------
  # 2. MART MODELS (BUSINESS LAYER)

  - name: mart_conflict_fatalities_by_country
    columns:
      - name: country
        tests: [not_null]

  - name: mart_global_trends_by_year
    columns:
      - name: conflict_year
        tests: [unique, not_null]
